restructured logging

diff --git a/bin/swl-launch b/bin/swl-launch
--- a/bin/swl-launch
+++ b/bin/swl-launch
@@ -2,7 +2,7 @@
 
 # Prevent running as root
 if [ "$(id -u)" -eq 0 ]; then
-    echo "ERROR: Do not run this script as root. Please run as a regular user." | tee -a "$LOGFILE"
+    echo "ERROR: Do not run this script as root. Please run as a regular user."
     exit 1
 fi
 
@@ -10,29 +10,29 @@ source /usr/lib/swl/setup-logging.sh
 
 export RESOLUTION=$(xdpyinfo | awk '/dimensions/{print $2}')
 if [ -z "$RESOLUTION" ]; then
-    echo "Failed to detect screen resolution. Exiting." | tee -a "$LOGFILE"
+    echo "Failed to detect screen resolution. Exiting."
     exit 1
 fi
 
-trap '/usr/bin/swl-shutdown-waydroid | tee -a "$LOGFILE"' EXIT
+trap /usr/bin/swl-shutdown-waydroid EXIT
 
 # Check if non Steam shortcut has the game / app as the launch option
 if [ -z "$1" ]
 then
     # launch option not provided. launch Waydroid via cage and show the full ui right away
-    echo "[$(date)] Launching Waydroid with full UI..." | tee -a "$LOGFILE"
+    echo "[$(date)] Launching Waydroid with full UI..."
     cage -- bash -c 'wlr-randr --output X11-1 --custom-mode $RESOLUTION ; \
         /usr/bin/swl-startup-waydroid ; \
-        /usr/bin/waydroid show-full-ui &' | tee -a "$LOGFILE"
+        /usr/bin/waydroid show-full-ui &'
 else
     # launch option provided. launch Waydroid via cage but do not show full ui, launch the app from the arguments, then launch the full ui so it doesnt crash when exiting the app provided
-    echo "[$(date)] Launching Waydroid app: $1 ..." | tee -a "$LOGFILE"
+    echo "[$(date)] Launching Waydroid app: $1 ..."
     cage -- env PACKAGE="$1" bash -c 'wlr-randr --output X11-1 --custom-mode $RESOLUTION ; \
         /usr/bin/swl-startup-waydroid ; \
         sleep 1 ; \
         /usr/bin/waydroid app launch $PACKAGE & \
         sleep 1 ; \
-        /usr/bin/waydroid show-full-ui &' | tee -a "$LOGFILE"
+        /usr/bin/waydroid show-full-ui &'
 fi
 
 # run shutdown scripts to cleanup when waydroid exits
